#!/usr/bin/env bash

# To run minitest with a seed value, do something like: ./_test TESTOPTS="--seed 41006"

clear
printf '\n***** START ***************************************************************************\n\n' >> log/test.log
if [ $# -eq 0 ] ; then
  time bin/rake test
else
  time bin/rake test "$*"
fi
printf '\n***** DONE ****************************************************************************\n\n' >> log/test.log
